In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

import warnings

In [23]:
df = pd.read_csv('dataJN/raw.csv')

In [24]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [25]:
# input feature
X = df.drop(columns=['math score'],axis=1)

In [26]:
X.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [27]:
# Output feature
Y = df['math score']

In [28]:
Y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [29]:
# Changing categorical features in numerical features

num_features = X.select_dtypes(exclude=object).columns
cat_features = X.select_dtypes(exclude=object).columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
cat_transfer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", cat_transfer, cat_features),
        ("StandardScaler",numeric_transformer, num_features)
    ]
)

In [30]:
X = preprocessor.fit_transform(X)

In [34]:
# Seprate dataset in train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((800, 151), (200, 151))

In [39]:
# Create an evaluate function to give all metrices after model training

def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_absolute_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2 = r2_score(true, predicted)

    return mae, rmse, r2

In [40]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, Y_train) # Train model

    # Make predictions
    Y_train_pred = model.predict(X_train)
    Y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(Y_train, Y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(Y_test, Y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 7.8301
- Mean Absolute Error: 6.2872
- R2 Score: 0.7280
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 9.7757
- Mean Absolute Error: 7.9516
- R2 Score: 0.6073
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 8.6808
- Mean Absolute Error: 6.9821
- R2 Score: 0.6658
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 8.8751
- Mean Absolute Error: 7.3635
- R2 Score: 0.6763
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 7.8737
- Mean Absolute Error: 6.3800
- R2 Score: 0.7250
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 9.3038
- Mean Absolute Error: 7.6834
- R2 Score: 0.6443
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 7.5873
- Mean Absolute Error: 6.1303
- R2 Score: 0.7447
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 9.9877
- Mean Absolute Error: 8.0130
- R2 Score: 0.5901
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 4.9302
- Mean Absolute Error: 2.9427
- R2 Score: 0.8922
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 11.5335
- Mean Absolute Error: 9.2951
- R2 Score: 0.4533
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 5.4866
- Mean Absolute Error: 4.1809
- R2 Score: 0.8665
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 10.2412
- Mean Absolute Error: 8.1971
- R2 Score: 0.5690
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 5.2954
- Mean Absolute Error: 3.8341
- R2 Score: 0.8756
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 10.6112
- Mean Absolute Error: 8.5824
- R2 Score: 0.5373
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 6.4089
- Mean Absolute Error: 5.2234
- R2 Score: 0.8178
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 9.5523
- Mean Absolute Error: 7.6596
- R2 Score: 0.6250
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 8.4030
- Mean Absolute Error: 6.9074
- R2 Score: 0.6868
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 8.9593
- Mean Absolute Error: 7.3664
- R2 Score: 0.6701
===================================